### ISSUE TITLE
Add to Gradle Plugin Portal

### ISSUE THREAD

**Issue by ben-manes** [joelittlejohn/jsonschema2pojo#282]
This should be done for discoverability to promote js2p and has no functionality changes. It is required if using the new plugin DSL, but that's not used in practice yet.

The [steps](https://plugins.gradle.org/docs/submit) appear minimal. It does require changing to the new Gradle plugin naming convention, so there is a little upgrade pain.

JCenter is a two-way mirror of Maven Central. Ideally this requires a small change to the build while still publishing as usual. If the new attributes can only be provided if publishing to JCenter directly, then this won't be worth the effort.

**Comment by Chessray** [comment]
Is there any work happening in this space? This plugin is the only reason for us to use the dreaded

``
buildscript {
  repositories {
    ...
  }
  dependencies {
    ...
  }
}
block on my current project. We'd really like to be able to use the plugin DSL for this gem as well.

**Comment by marekjagielski** [comment]
Are there any plans for adding plugin to Plugin Portal?

**Comment by Enigamitsuj** [comment]
Had a similar issue here is how I solved it. Voting this up!
https://stackoverflow.com/questions/51766423/cant-use-jsonschema2pojo-gradle-plugin-in-plugins-block

**Comment by EAlf91** [comment]
@Enigamitsuj solution works, but is another workaround. Any plans to work on this?

**Comment by joelittlejohn** [comment]
I've published v1.1.3 to plugins.gradle.org. There's a problem somewhere but I've been unable to track it down yet.

When I use [legacy plugin application](https://docs.gradle.org/current/userguide/plugins.html#sec:old_plugin_application) then I can use the plugin successfully. When I use the [newer plugin DSL](https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block) then I see this error:

```
* What went wrong:
Could not apply requested plugin [id: 'org.jsonschema2pojo', version: '1.1.3'] as it does not provide a 
plugin with id 'org.jsonschema2pojo'. This is caused by an incorrect plugin implementation. Please 
contact the plugin author(s).
> Plugin with id 'org.jsonschema2pojo' not found.
```

Clearly there is something not quite right with the metadata, or there is some conflict with what is published to plugins.gradle.org and what is published to Maven Central. Unfortunately Gradle doesn't give much useful info ([this is the exception](https://github.com/gradle/gradle/blob/v7.6.0/subprojects/core/src/main/java/org/gradle/api/internal/plugins/DefaultPluginManager.java#L144)).

Should be easy to fix I'm sure. I will leave the plugin published for now (for diagnostic purposes), but will take it down within 7 days if I don't resolve the problem.

**Comment by ben-manes** [comment]
At some point Gradle deprecated being able to use unqualified plugin ids like `jsonschema2pojo` except for internal plugins and adopted reverse domain names. Since this plugin predates that I am guessing it is beyond the sunset period (as plugin block came even later) so it is rejected. I believe you would just need to bite the bullet and force users to update.

**Comment by unkish** [comment]
```gradle
plugins {
    id 'java'
    id "org.jsonschema2pojo" version "1.1.3"
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.14.2'
}

test {
    useJUnitPlatform()
}
```
as well as 
```gradle
buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "org.jsonschema2pojo:jsonschema2pojo-gradle-plugin:1.1.3"
    }
}

plugins {
    id 'java'
}

apply plugin: "org.jsonschema2pojo"

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.14.2'
}

test {
    useJUnitPlatform()
}
```

Worked for me 🤔

**Comment by ben-manes** [comment]
I was able to reproduce the problem. The issue is the ordering of buildscript repositories. If Maven Central is the first on the list then the plugin id does not resolve. If the Gralde Plugin Portal is the first then it does. The released artifact metadata differs between the repositories ([central](https://repo1.maven.org/maven2/org/jsonschema2pojo/jsonschema2pojo-gradle-plugin/1.1.3/), [portal](https://plugins.gradle.org/m2/org/jsonschema2pojo/jsonschema2pojo-gradle-plugin/1.1.3/)) and is somehow causing resolution differences.

**Comment by joelittlejohn** [comment]
Ah yes, so the jar on Central contains this:

![image](https://user-images.githubusercontent.com/686384/218591266-ba3314ce-0aba-4d51-a2cf-6265034e22fd.png)

and the jar on portal contains this:

![image](https://user-images.githubusercontent.com/686384/218591347-5522ad4a-0ae3-43c3-86c3-7fa87af82dfe.png)

Looks like we just need the org.jsonschema2pojo.properties present in the Central jar. Should be trivial to fix.

Thanks for investigating @ben-manes !
